
SET APP_NAME = '&{APP_NAME}';
SET APP_PKG_NAME = 'ILEVEL_CONNECTOR_PKG' ;

-- Create stage
CREATE DATABASE IF NOT EXISTS IDENTIFIER('&STAGE_DB');
CREATE STAGE IF NOT EXISTS IDENTIFIER('&STAGE_NAME');

PUT 'file://sf_build/*' @&{STAGE_NAME}/&{APP_VERSION} AUTO_COMPRESS = FALSE overwrite=true;

-- ALTER APPLICATION PACKAGE IDENTIFIER($APP_PKG_NAME) DROP VERSION &APP_VERSION; -- ADDED RECENTLY 

-- DROP APPLICATION PACKAGE IF EXISTS IDENTIFIER($APP_PKG_NAME);
CREATE APPLICATION PACKAGE IF NOT EXISTS IDENTIFIER($APP_PKG_NAME);


ALTER APPLICATION PACKAGE IDENTIFIER($APP_PKG_NAME) ADD VERSION &APP_VERSION USING @&{STAGE_NAME}/&APP_VERSION;


