
SET WAREHOUSE = '&{WAREHOUSE}';

SET APP_PKG_NAME = 'ILEVEL_CONNECTOR_PKG';


USE DATABASE ILEVEL_CONNECTOR_STAGE;


-- CREATE OR REPLACE NETWORK RULE ILEVEL_RULE  
-- MODE = EGRESS
-- TYPE = HOST_PORT
-- VALUE_LIST=('api.ilevelsolutions.com:443');  

-- CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION ILEVEL_INTEGRATION  
-- ALLOWED_NETWORK_RULES = (ILEVEL_RULE)
-- allowed_authentication_secrets = all --#*#*#* THIS ALLOWS ALL SECRETS TO BE USED
-- ENABLED = TRUE ; 


-- DROP APPLICATION IF EXISTS "ILEVEL_CONNECTOR"  CASCADE;
-- CREATE APPLICATION "ILEVEL_CONNECTOR" FROM APPLICATION PACKAGE IDENTIFIER($APP_PKG_NAME) USING VERSION &APP_VERSION;


 ALTER APPLICATION ILEVEL_CONNECTOR UPGRADE USING VERSION &APP_VERSION  ; 


